* Balanceamento por Semirreações

** Balanceamento por Semirreações

- 1 :: Mas a maioria é complicada. O melhor método de se balancear uma reação redox é através do *método das semirreações*.
- 2 :: Isto envolve considerar (apenas no papel) que a redução e a oxidação são dois processos separados.
- 3 :: Balanceia-se as reações para estes processos, combinando-as no final para se obter a equação balanceada da reação global.

** Etapas do Balancemanto 

- 1) :: Atribua os números de oxidação para verificar o que é oxidado e o que é reduzido.
- 2) :: Escreva as semirreações de oxidação e de redução.
- 3) :: Balanceie cada semirreação
  #+ATTR_LATEX: :options [logo=\bcattention, noborder=true, barre=none]{Atenção}
  #+begin_bclogo 
- Balanceie os elementos diferentes de H e O.
- Balanceie O adicionando \ch{H2O}.
- Balanceie H adicionando \ch{H+}.
- Balanceie a carga adicionando elétrons.
  #+end_bclogo
- 4) :: Multiplique as semirreações por números inteiros de modo que o número de elétrons ganhos seja igual ao número de elétrons perdidos.
- 5) :: Some as semirreações, subtraindo as espécies que aparecem dos dois lados.
- 6) :: Certifique-se de que a equação está balanceada em *massa*.
- 7) :: Certifique-se de que a equação está balanceada em *carga*.

** Exemplo I

Considere a reação entre @@latex: \ch{HC$\ell$3^−}@@ e @@latex: \ch{Cr2O7^{2-}}@@:

#+begin_export latex
\begin{reaction*}
HC$\ell$O^-_{\aq} + Cr2O7^{2-}_{\aq} -> C$\ell$O3^{-}_{\aq}  + Cr^{+3}_{\aq}
\end{reaction*}
#+end_export

#+ATTR_LATEX: :options [logo=\bcinfo, noborder=true, barre=none]{Semirreação Oxidação}
#+begin_bclogo
#+begin_export latex
\ch{HC$\ell$O -> C$\ell$O3^⁻}
#+end_export
#+end_bclogo




