* Funções Oxigenadas

** Definição

#+begin_export latex
\begin{center}
\scalebox{.65}{
\begin{tikzpicture}[mindmap, grow cyclic, every node/.style=concept, concept color=orange!40, 
	level 1/.append style={level distance=5cm,sibling angle=35},
	level 2/.append style={level distance=2.8cm,sibling angle=90},]

	\node {Funções \\ Oxigendas}
	child {node [concept color = blue!40] {Álcoois}
	%	child {node [concept color = teal!30] {\chemfig{R-OH} \\ }}
	}
	child [concept color = blue!30] {node {Áldeído}
		%	child [concept color = teal!30, xshift=.5cm, yshift=1cm, text width=2.1cm,] {node {\chemfig{R-[:30](=[:90]O)-[:330]H}}}
	}
	child {node [concept color = blue!30] {Cetonas}
		%child [concept color = teal!30, xshift=.3cm, yshift=.3cm, text width=2.2cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]R}  }}
	}
	child [concept color = blue!30] {node {Enol}
%		child [concept color = teal!30, xshift=.3cm, yshift=.3cm, text width=2.2cm] {node {\chemfig{R-[:30](-[:90]OH)=[:330]R}  }}
	}
	child [concept color = blue!30] {node {Éster}
	%			child [concept color = teal!30, xshift=1.5cm, yshift=1cm, text width=3.3cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]O-R}}}
	}
	child [concept color = blue!30] {node {Éter}
		%		child [concept color = teal!30,xshift=.5cm, yshift=1cm, text width=2.5cm] {node {\chemfig{R-O-R}}}
	}
	child [concept color = blue!30] {node {Ácido \\ Carboxílico}
			%	child [concept color = teal!30, xshift=1.5cm, yshift=1cm, text width=3.cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]OH}}}
	}
	child [concept color = blue!30] {node {Fenóis}
				%child [concept color = teal!30, xshift=.5cm, yshift=.5cm, text width=2.2cm] {node {\chemfig{**6(----(-OH)--)}  }}		
	}
	child [concept color = blue!30] {node {Sais \\ Orgânicos}
				%child [concept color = teal!30, xshift=1.5cm, yshift=1cm, text width=3.cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]O-Metal}}}
	}
	child [concept color = blue!30] {node {Anidridos}
				%child [concept color = teal!30, xshift=1.5cm, yshift=.3cm, text width=4.2cm] {node {\chemfig{R-[:150](=[:90]O)-[:210]O-[:150](-[:210]R)=[:90]O}}}
};
	
\end{tikzpicture}
}
\end{center}
#+end_export

** Álcoois

Substâncias  orgânicas  que  apresentam  hidroxila  ou oxidrila (\ch{-OH}) ligada ao C saturado ($sp^3$).


  #+begin_export latex
  \begin{center}
% \chemfig{-C([:-90]-)([:90]-)-{\color{red}OH}}
\chemfig{-C([:90]-)([:-90]-)-[@{b1,0}]{\color{red}O}@{H}{\color{red}H}}
%\chemfig{C(-[2]H)(-[4]H)(-[6]H)-C(-[2]H)(-[6]H)-[@{b1,0}]O@{H}H}
\chemmove{
	\draw[-,magenta]
	(b1) -- ++(0,.45) -| (H.east)
	(b1) -- ++(0,-.45) -| (H.east) ;
}
Grupo Funcional

 \end{center}
  #+end_export 


#+ATTR_LATEX: :options [couleur=yellow!30 , arrondi=0.1 , logo=\bcplume , epBarre=3.5]{Exemplo}
#+begin_bclogo

  #+begin_export latex
  
\schemestart
\scriptsize
\chemname{\chemfig{H_3C-CH_2-OH}}{Álcool alifático} \qquad \qquad \chemname{\chemfig{H_2C([:-90]-OH)-CH_2([:-90]-OH)}}{Diálcool alifático} \qquad \qquad 
\chemname{\chemfig{*6(---(-OH)---)}}{Álcool cíclico} \qquad \qquad 
\chemname{\chemfig{*6(-=-(-OH)=-=)}}{Álcool aromático}
\schemestop
  #+end_export
#+end_bclogo



** Classificação

#+ATTR_LATEX: :options [couleur=yellow!30 , arrondi=0.1 , logo=\bcplume , epBarre=3.5]{Quanto ao número de hidroxilas}
#+begin_bclogo
#+begin_export latex
\schemestart
\scriptsize
\chemname{\chemfig{H_3C-CH_2-OH}}{Monoálcool} \qquad \qquad \chemname{\chemfig{CH_2([:-90]-OH)-CH_2([:-90]-OH)}}{Diálcool} \qquad \qquad
\chemname{\chemfig{CH_2([:-90]-OH)-CH([:-90]-OH)-CH_2([:-90]-OH)}}{Triálcool} \qquad \qquad 
\chemname{\chemfig{HO-[:30,,2](<[:90,,,1]OH)-[:330](<:[:270,,,1]OH)-[:30](%
-[:330,,,1]OH)<[:90,,,1]OH}}{Poliálcool}
\schemestop
#+end_export
#+end_bclogo
  





#+ATTR_LATEX: :options [couleur=yellow!30 , arrondi=0.1 , logo=\bcplume , epBarre=3.5]{Quanto ao tipo de carbono que contém a hidroxila}
#+begin_bclogo
#+begin_export latex
\scriptsize
\schemestart
\chemname{\chemfig{H_3C-CH_2-OH}}{Álcool primário} \qquad \qquad 
\chemname{\chemfig{H_3C-CH([:90]-OH)-CH_3}}{Álcool secundário} \qquad \qquad 
\chemname{\chemfig{H_3C-C([:-90]-CH_3)([:90]-OH)-CH_3}}{Álcool terciário} 
\schemestop

#+end_export
#+end_bclogo


  
** Nomenclatura

- Segue as mesmas regras estabelecidas para os Hidrocarbonetos; a única diferença é a terminação

  #+begin_export latex

\begin{tblr}
[
theme= fancy,
]
{
colspec = {ccc}, colsep = 10mm, hlines = {2pt, white},
row{1} = {2em,azure3,fg=white,font=\bfseries\sffamily},
}
\hline 
Prefixo & Intermediário & Sufixo \\
Número de carbonos & tipo de ligação & \alert{ol}\\
\hline
\end{tblr}
  #+end_export

- A cadeia principal deve ser a mais longa que contém o carbono ligado ao OH;
- A numeração da cadeia deve se iniciar pela extremidade mais próxima ao OH;
- Se necessário, indicar a posição do grupo OH.
  
#+begin_export latex
\begin{bclogo}[couleur=yellow!30, arrondi=0.1, logo=\bcplume, epBarre=3.5]{Exemplo} 
\schemestart
\chemfig{CH_3-CH_2-OH}
\arrow
\chemleft. 
\subscheme
{\begin{tabular}{lc}
2 carbonos & \ch{->} \textcolor{blue}{\bfseries et}\\
lig. simples & \ch{->} \textcolor{green}{\bfseries an}\\
álcool & \ch{->} \textcolor{red}{\bfseries ol}\\
\end{tabular}
}
\chemright\}
%\node {A};
\schemestop
\chemmove{
\node[draw,right= of c3,fill=orange,text=white,font=\Large\bfseries] (o1) {Etanol};
}
\end{bclogo}

#+end_export



** Exemplos de Álcoois



#+begin_export latex
\begin{bclogo}[couleur=yellow!30, arrondi=0.1, logo=\bcplume, epBarre=3.5]{Exemplo} 


 
\scriptsize{
\schemestart
\chemfig[atom style={rotate=0}]{@{o1}\chemabove{C}{\color{blue}{1}}H_3-\chemabove{C}{\color{blue}{2}}H([:-90]-CH_3)-\chemabove{C}{\color{blue}{3}}@{o2}H_2-OH}
\arrow
\chemleft. 
\subscheme
{\begin{tabular}{lc}
3 carbonos & \ch{->} \textcolor{blue}{\bfseries prop}\\
lig. simples & \ch{->} \textcolor{green}{\bfseries an}\\
álcool & \ch{->} \textcolor{red}{\bfseries ol}\\
Radical metil & \ch{->} {\bfseries 2-metil} \\
\end{tabular}
}
\chemright\}
%\node {A};
\schemestop
\chemmove{
\node[draw,right= of c3,fill=orange,text=white,font=\bfseries] (01) {2-metil-propan-1-ol};
\node[inner sep=2pt,fill=red,fill opacity=0.2,fit= (o1) (o2)]{};
}
}

\vspace{.5cm}

\schemestart
\chemfig{@{a1}H_3\mcfabove{C}{\mcfatomno{5}}-\mcfabove{C}{\mcfatomno{4}}H([:-90]-CH_3)-\mcfabove{C}{\mcfatomno{3}}H_2-\mcfabove{C}{\mcfatomno{2}}H([:-90]-OH)-\mcfabove{C}{\mcfatomno{1}}H_3@{a2}}
\arrow
%\chemleft. 
%\chemright\}
\schemestop
\chemmove{
\node[draw,right= 1cm of c1,fill=orange,text=white,font=\bfseries] (01) {4-metil-pentan-2-ol};
\node[inner sep=2pt,fill=red,fill opacity=0.2,fit= (a1) (a2)]{};
}

\vspace{.5cm}

\schemestart
\chemfig{H_3\mcfabove{C}{\mcfatomno{1}}-\mcfabove{C}{\mcfatomno{2}}H([:-90]-CH_3)-\mcfbelow{C}{\mcfatomno{3}}H([:90]-OH)-\mcfabove{C}{\mcfatomno{4}}H([:-90]-CH_2-CH_3)-\mcfbelow{C}{\mcfatomno{5}}H([:90]-CH_3)-\mcfabove{C}{\mcfatomno{6}}H_2-\mcfabove{C}{\mcfatomno{7}}H_3}
\arrow{->} 
\chemmove{
\node[draw,right=1cm  of c1,fill=orange,text=white,font=\bfseries] (01) {4-etil-2,5-dimetil-heptan-3-ol};
}
\schemestop




\end{bclogo}
#+end_export



** 

#+begin_export  latex
\small{
\schemestart
\chemup.
\chemfig{CH_2([:90]-OH)-CH_2-CH([:90]-OH)-CH_3}
\chemdown\}
%%% Ciclopentanol
\arrow(s1--)[-90,1.3,,,draw=none]
\subscheme{
\chemup.
\chemfig{*5(---(-OH)--)}
\chemdown\}
%%% ciclo
\arrow(s2--)[,1.5,,,draw=none] 
}
\arrow(@s2--)[,1.8,,,draw=none]
\chemup.
\chemfig{CH_3-[:270,,1]-[:330]-[:270](-[:330,,,1]OH)-[:210]-[:150]-[:90](%
-[:30])}
\chemdown\}
%% ESQUEMA C2 LADO DIREITO
\arrow(@s1--)[,2.3,,,draw=none]
\subscheme{
\chemup.
\chemfig{H_2C=C([:-90]-CH_3)-CH_2-CH_2([:90]-OH)}
\chemdown\}
}
%SETA DO ESQUEMA 2 X 2
\arrow(s4--)[-90,1.,,,draw=none]
\subscheme{
\chemup. 
\chemfig{*4(-(-OH)--(-CH_3)-)}
\chemdown\}
} 
\schemestop
\chemmove{
\node[draw,below= .2cm of s1,fill=orange,text=white,font=\bfseries] (01) {Butan-1,3-diol};
\node[draw,below= .15cm of s2,fill=orange,text=white,font=\bfseries] (01) {ciclopentanol};
\node[draw,below= .15cm of s4,fill=orange,text=white,font=\bfseries] (01) {3-metilbut-3-en-1-ol};
\node[draw,below= .15cm of c4,fill=orange,text=white,font=\bfseries] (01) {3-metilciclohexan-1-  ol};
\node[draw,below= .15cm of c7,fill=orange,text=white,font=\bfseries] (01) {3-metilciclobutanol};
}
}
#+end_export


** 

Em moléculas mais complicadas, a nomenclatura IUPAC considera a *oxidrila* como sendo uma ramificação, chamada de *hidróxi*.

#+begin_export latex

\schemestart
\chemfig{[:30]*6(-=(-@{a1}\mcfabove{C}{\mcfatomno{1}}H_2-\mcfabove{C}{\mcfatomno{2}}H([:-90]-OH)-\mcfabove{C}{\mcfatomno{3}}H([:-90]-C{\ell})-\mcfabove{C}{\mcfatomno{4}}H_3@{a2})-=-=-)}
\schemestop
\chemmove{
\node[inner sep=2.5pt,fill=red,fill opacity=0.2,fit=(a1) (a2)]{};
\node[draw,below= .2cm of c1,fill=orange,text=white,font=\large\bfseries] (01) {3-cloro-1-fenil-2-hidróxi-butano};
}
#+end_export
