* Funções Oxigenadas
** Definição

#+begin_export latex
\begin{center}
\scalebox{.65}{
\begin{tikzpicture}[mindmap, grow cyclic, every node/.style=concept, concept color=orange!40, 
	level 1/.append style={level distance=5cm,sibling angle=35},
	level 2/.append style={level distance=2.8cm,sibling angle=90},]

	\node {Funções \\ Oxigendas}
	child {node [concept color = blue!40] {Álcoois}
	%	child {node [concept color = teal!30] {\chemfig{R-OH} \\ }}
	}
	child [concept color = blue!30] {node {Áldeído}
		%	child [concept color = teal!30, xshift=.5cm, yshift=1cm, text width=2.1cm,] {node {\chemfig{R-[:30](=[:90]O)-[:330]H}}}
	}
	child {node [concept color = blue!30] {Cetonas}
		%child [concept color = teal!30, xshift=.3cm, yshift=.3cm, text width=2.2cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]R}  }}
	}
	child [concept color = blue!30] {node {Enol}
%		child [concept color = teal!30, xshift=.3cm, yshift=.3cm, text width=2.2cm] {node {\chemfig{R-[:30](-[:90]OH)=[:330]R}  }}
	}
	child [concept color = blue!30] {node {Éster}
	%			child [concept color = teal!30, xshift=1.5cm, yshift=1cm, text width=3.3cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]O-R}}}
	}
	child [concept color = blue!30] {node {Éter}
		%		child [concept color = teal!30,xshift=.5cm, yshift=1cm, text width=2.5cm] {node {\chemfig{R-O-R}}}
	}
	child [concept color = blue!30] {node {Ácido \\ Carboxílico}
			%	child [concept color = teal!30, xshift=1.5cm, yshift=1cm, text width=3.cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]OH}}}
	}
	child [concept color = blue!30] {node {Fenóis}
				%child [concept color = teal!30, xshift=.5cm, yshift=.5cm, text width=2.2cm] {node {\chemfig{**6(----(-OH)--)}  }}		
	}
	child [concept color = blue!30] {node {Sais \\ Orgânicos}
				%child [concept color = teal!30, xshift=1.5cm, yshift=1cm, text width=3.cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]O-Metal}}}
	}
	child [concept color = blue!30] {node {Anidridos}
				%child [concept color = teal!30, xshift=1.5cm, yshift=.3cm, text width=4.2cm] {node {\chemfig{R-[:150](=[:90]O)-[:210]O-[:150](-[:210]R)=[:90]O}}}
};
	
\end{tikzpicture}
}
\end{center}
#+end_export




* Álcool
** Álcool
  #+latex: \begin{mybox}{Álcool}
  Substâncias  orgânicas  que  apresentam  hidroxila  ou oxidrila (-OH) ligada ao C saturado ($sp^3$).


  #+begin_export latex
  \begin{center}
% \chemfig{-C([:-90]-)([:90]-)-{\color{red}OH}}
\chemfig{-C([:90]-)([:-90]-)-[@{b1,0}]{\color{red}O}@{H}{\color{red}H}}
%\chemfig{C(-[2]H)(-[4]H)(-[6]H)-C(-[2]H)(-[6]H)-[@{b1,0}]O@{H}H}
\chemmove{
	\draw[-,magenta]
	(b1) -- ++(0,.45) -| (H.east)
	(b1) -- ++(0,-.45) -| (H.east) ;
}
Grupo Funcional
 \end{center}
  #+end_export 
  
  #+latex: \end{mybox}


** Fórmulas e aplicações álcoois
   
   


      
* Enol
** Enóis
     #+latex: \begin{mybox}{Enol}
  Substâncias  orgânicas  que  apresentam  hidroxila  ou oxidrila (-OH) ligada ao C com uma dupla ligação.


  #+begin_export latex
  \begin{center}
\schemestart
\chemfig{-@{OH1}C([:90]-)([:-90]-)=C([:90]-)([:-90]-)-O@{OH2}H}
\schemestop
\chemmove{
	\node[inner sep=2pt,fill=red,fill opacity=0.2,fit=(OH1) (OH2)]{};
    }
    \end{center}
#+end_export 

  #+latex: \end{mybox}
     #+begin_export latex
   \begin{myex}{Exemplo}
 \begin{center}  
 %  \chemname{
%   \chemfig{H_3{\color{red}C}-OH}}{{\color{red}Met}anol}\hspace{1cm}
   \chemname{
   \vspace{.3cm}
\chemfig{
           \mcfleft{\mcfatomno{4}}{C}H_3% 4
     -[:0]\mcfabove{C}{\mcfatomno{3}}H_2% 3
    -[:0]\mcfabove{C}{\mcfatomno{2}}H% 2
     =[:0]\mcfabove{C}{\mcfatomno{1}}H% 1
    -[:0]OH}% 
}
{But-1-en-1-ol}
\end{center}\
%
\end{myex}
#+end_export
   


* Fenol
**  Fenóis
#+latex: \begin{mybox}{Fenol}
  Substâncias  orgânicas  que  apresentam  hidroxila  ou oxidrila (-OH) ligada ao carbono do anel aromático.


  #+begin_export latex

\begin{tikzpicture}
\tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{*6(-=-=-(-OH)=-)}} \af
\tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{**6(-----(-OH)--)}} \af
\end{tikzpicture}

  #+end_export 
  #+latex: \end{mybox}

** Tipos de fénois
   #+begin_export latex
   \begin{myex}{Fénois}
   \centering
   \chemname{\chemfig{*6(-=(-OH)-=-=)}}{Hidroxi \\ Benzeno} \af 
   \chemname{\chemfig{**6(---(**6(------))---)}}{Naftaleno} \af 
   \chemname{\chemfig{**6(--(**6(-**6(------)-----))----)}}{Antraceno}
   \end{myex}
   #+end_export
   

* Aldeídos
** Aldeídos
   #+latex: \begin{mybox}{Aldeído}
   Os aldeídos apresentam o grupo carbonila na extremidade da cadeia.   


   #+begin_export latex
   \begin{center}
\begin{tikzpicture}
\tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{-[:30]-[:330]-[:30](-[:330,,,1]H)=[:90]O}} \hspace{.3 cm}
%\tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{**6(-----(-OH)--)}}
\end{tikzpicture}
\end{center}
   #+end_export
   #+latex: \end{mybox}   
   

** Nomenclatura dos Aldeídos


#+begin_export latex

\chemfig{H-[:150]\mcfatomno{1}(%
=[:90]O)-[:210]\mcfatomno{2}-[:150]\mcfatomno{3}}


#+end_export
   
* Cetonas

** Cetonas

#+latex: \begin{mybox}{Cetonas}
As cetonas apresentam o grupo carbonila,sendo este carbono secundário.
#+begin_export latex
   \begin{center}
   \begin{tikzpicture}
   \tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{C-C([:90]=O)-C}} \hspace{.3 cm}
   \end{tikzpicture}
   \end{center}
   #+end_export
#+latex: \end{mybox}
   

* Ácido Carboxílicos
** Ácidos Carboxílicos
    #+latex: \begin{mybox}{Ácidos Carboxílicos}
   Os ácidos carboxílicos são compostos caracterizados pela  presença do grupo *carboxila*, formado pela união dos grupos carbonila e hidroxila.


   #+begin_export latex
   \begin{center}
   \begin{tikzpicture}
   \tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{-C([:30]=O)([:330]-OH)}} \hspace{.3 cm}
   \end{tikzpicture}
   \end{center}
   #+end_export
   #+latex: \end{mybox}   


* Ésteres
    #+latex: \begin{mybox}{Ésteres}
    Os ésteres orgânicos são caracterizados pelo grupo funcional:
   #+begin_export latex
   \begin{center}
   \begin{tikzpicture}
   \tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{R-C([:90]=O)-O-R'}} \hspace{.3 cm}
   \end{tikzpicture}
   \end{center}
   #+end_export
   Simplificadamente podemos considerar queos ésteres
   se originam a partir da substituição do hidrogênio do grupo OH de um
   ácido carboxílico por um radical orgânico (R).
   #+latex: \end{mybox}

   
* Éteres

** Éteres

    #+latex: \begin{mybox}{Éteres}
Os éteres apresentam um átomo de oxigênio(O) ligado a dois radicais orgânicos.
Seu grupo funcional é representado por:

#+begin_export latex
   \begin{center}
   \begin{tikzpicture}
   \tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{R-O-R'}} \hspace{.3 cm}
   \end{tikzpicture}
   \end{center}
   #+end_export

   #+latex: \end{mybox}





* Anidridos

** Anidridos



