* Funções Oxigenadas
** Definição


#+begin_export latex
\begin{center}
\scalebox{.65}{
\begin{tikzpicture}[mindmap, grow cyclic, every node/.style=concept, concept color=orange!40, 
	level 1/.append style={level distance=5cm,sibling angle=35},
	level 2/.append style={level distance=2.8cm,sibling angle=90},]

	\node {Funções \\ Oxigendas}
	child {node [concept color = blue!40] {Álcoois}
	%	child {node [concept color = teal!30] {\chemfig{R-OH} \\ }}
	}
	child [concept color = blue!30] {node {Áldeído}
		%	child [concept color = teal!30, xshift=.5cm, yshift=1cm, text width=2.1cm,] {node {\chemfig{R-[:30](=[:90]O)-[:330]H}}}
	}
	child {node [concept color = blue!30] {Cetonas}
		%child [concept color = teal!30, xshift=.3cm, yshift=.3cm, text width=2.2cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]R}  }}
	}
	child [concept color = blue!30] {node {Enol}
%		child [concept color = teal!30, xshift=.3cm, yshift=.3cm, text width=2.2cm] {node {\chemfig{R-[:30](-[:90]OH)=[:330]R}  }}
	}
	child [concept color = blue!30] {node {Éster}
	%			child [concept color = teal!30, xshift=1.5cm, yshift=1cm, text width=3.3cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]O-R}}}
	}
	child [concept color = blue!30] {node {Éter}
		%		child [concept color = teal!30,xshift=.5cm, yshift=1cm, text width=2.5cm] {node {\chemfig{R-O-R}}}
	}
	child [concept color = blue!30] {node {Ácido \\ Carboxílico}
			%	child [concept color = teal!30, xshift=1.5cm, yshift=1cm, text width=3.cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]OH}}}
	}
	child [concept color = blue!30] {node {Fenóis}
				%child [concept color = teal!30, xshift=.5cm, yshift=.5cm, text width=2.2cm] {node {\chemfig{**6(----(-OH)--)}  }}		
	}
	child [concept color = blue!30] {node {Sais \\ Orgânicos}
				%child [concept color = teal!30, xshift=1.5cm, yshift=1cm, text width=3.cm] {node {\chemfig{R-[:30](=[:90]O)-[:330]O-Metal}}}
	}
	child [concept color = blue!30] {node {Anidridos}
				%child [concept color = teal!30, xshift=1.5cm, yshift=.3cm, text width=4.2cm] {node {\chemfig{R-[:150](=[:90]O)-[:210]O-[:150](-[:210]R)=[:90]O}}}
};
	
\end{tikzpicture}
}
\end{center}
#+end_export




* Álcool
** Álcool
  #+latex: \begin{mybox}{Álcool}
  Substâncias  orgânicas  que  apresentam  hidroxila  ou oxidrila (-OH) ligada ao C saturado ($sp^3$).


  #+begin_export latex
  \begin{center}
% \chemfig{-C([:-90]-)([:90]-)-{\color{red}OH}}
\chemfig{-C([:90]-)([:-90]-)-[@{b1,0}]{\color{red}O}@{H}{\color{red}H}}
%\chemfig{C(-[2]H)(-[4]H)(-[6]H)-C(-[2]H)(-[6]H)-[@{b1,0}]O@{H}H}
\chemmove{
	\draw[-,magenta]
	(b1) -- ++(0,.45) -| (H.east)
	(b1) -- ++(0,-.45) -| (H.east) ;
}
Grupo Funcional
 \end{center}
  #+end_export 
  
  #+latex: \end{mybox}


** Classificação do álcoois I
   
   #+begin_export latex
   \begin{myrule}{Critérios}
\begin{itemize}
\item  Posição do radical
%\item Quantidade de radicais oxidrilas
\end{itemize}
   \end{myrule}
   #+end_export

   
#+begin_export latex
\begin{myex}{Exemplo}
\chemname{\chemfig[atom style={scale=.8}]{H_3C-C([:90]-H)([:-90]-H)-OH}}{Carbono Primário} \af 
\qquad \chemname{\chemfig[atom style={scale=.8}]{H_3C-C([:90]-OH)([:-90]-H)-CH_3}}{Carbono Secundário} \af
\qquad \chemname{\chemfig[atom style={scale=.8}]{H_3C-C([:90]-CH_3)([:-90]-OH)-CH_3}}{Carbono Terciário}
\end{myex}
#+end_export

** Classificação do álcoois II

   #+latex: \begin{myrule}{Número de oxidrilas}

   - Monoálcoois ou monóis: apresentam uma oxidrila
   - Diálcoois ou dióis: apresentam duas oxidrilas
   - Triálcoois ou trióis: apresentam três oxidrilas
   
   #+latex: \end{myrule}

   #+begin_export latex
\begin{myex}{Exemplo}
\chemname{\chemfig[atom style={scale=.8}]{H_3C-C([:90]-H)([:-90]-H)-{\color{red}OH}}}{Monol} \af
\chemname{\chemfig[atom style={scale=.8}]{H_3C-C([:90]-H)([:-90]-{\color{red}OH})-{\color{red}OH}}}{Diol} \af
\chemname{\chemfig[atom style={scale=.8}]{H_3C-C([:90]-{\color{red}OH})([:-90]-{\color{red}OH})-{\color{red}OH}}}{Triol}
\end{myex}
   #+end_export
   
** Nomenclatura do álcoois

   #+begin_export latex

\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt        

\begin{tikzpicture}[x=0.75pt,y=0.75pt,yscale=-1,xscale=1]
%uncomment if require: \path (0,300); %set diagram left start at 0, and has height of 300

%Shape: Ellipse [id:dp5361300348946546] 
\draw  [fill={rgb, 255:red, 79; green, 209; blue, 180 }  ,fill opacity=1 ] (39,183.5) .. controls (39,147.88) and (65.32,119) .. (97.78,119) .. controls (130.25,119) and (156.56,147.88) .. (156.56,183.5) .. controls (156.56,219.12) and (130.25,248) .. (97.78,248) .. controls (65.32,248) and (39,219.12) .. (39,183.5) -- cycle ;
%Shape: Ellipse [id:dp6942133129332804] 
\draw  [fill={rgb, 255:red, 147; green, 243; blue, 125 }  ,fill opacity=1 ] (200.14,183.5) .. controls (200.14,147.88) and (226.45,119) .. (258.92,119) .. controls (291.38,119) and (317.7,147.88) .. (317.7,183.5) .. controls (317.7,219.12) and (291.38,248) .. (258.92,248) .. controls (226.45,248) and (200.14,219.12) .. (200.14,183.5) -- cycle ;
%Shape: Ellipse [id:dp9270081825456703] 
\draw  [fill={rgb, 255:red, 159; green, 192; blue, 246 }  ,fill opacity=1 ] (356.44,183.5) .. controls (356.44,147.88) and (382.75,119) .. (415.22,119) .. controls (447.68,119) and (474,147.88) .. (474,183.5) .. controls (474,219.12) and (447.68,248) .. (415.22,248) .. controls (382.75,248) and (356.44,219.12) .. (356.44,183.5) -- cycle ;

% Text Node
\draw (56.5,150.34) node [anchor=north west][inner sep=0.75pt]   [align=left] {\begin{minipage}[lt]{58.332644pt}\setlength\topsep{0pt}
\begin{center}
Quantidade \\de\\Carbonos
\end{center}

\end{minipage}};
% Text Node
\draw (167.94,166.08) node [anchor=north west][inner sep=0.75pt]   [align=left] {+};
% Text Node
\draw (330.2,167.39) node [anchor=north west][inner sep=0.75pt]   [align=left] {+};
% Text Node
\draw (233.28,152.97) node [anchor=north west][inner sep=0.75pt]   [align=left] {\begin{minipage}[lt]{39.043356pt}\setlength\topsep{0pt}
\begin{center}
Tipo \\de\\Ligação
\end{center}

\end{minipage}};
% Text Node
\draw (364.96,165.29) node [anchor=north west][inner sep=0.75pt]   [align=left] {\begin{minipage}[lt]{71.93244pt}\setlength\topsep{0pt}
\begin{center}
Grupo fucional \\ \alert{ol}
\end{center}

\end{minipage}};


\end{tikzpicture}

   #+end_export

   #+begin_export latex 
   \begin{myex}{Regra}
   \chemname{
   \chemfig{H_3{\color{red}C}-OH}}{{\color{red}Met}anol}\hspace{1cm}
   \chemname{
   \vspace{.3cm}
\chemfig{
           \mcfleft{\mcfatomno{4}}{C}H_3% 4
     -[:0]\mcfabove{C}{\mcfatomno{3}}H_2% 3
    -[:0]\mcfabove{C}{\mcfatomno{2}}H_2% 2
     -[:0]\mcfabove{C}{\mcfatomno{1}}H_2% 1
    -[:0]OH}% 
}
{Butan-1-ol}
   \end{myex}
   #+end_export

** Outros Exemplos
:PROPERTIES:
:BEAMER_opt: allowframebreaks
:END:
  
   #+latex: \begin{myrule}{}

   - Escolher a cadeia com o maior número de carbonos.
   - Enumerar o mais prćximo da hidroxila.
   - Separar os radicais, usar di, tri, tetra ... quando os radicais forem iguais.
   - Seguir ordem alfabética para os radicais.      


   #+begin_export latex
   \begin{center}
   \chemname{
   \chemfig{H_3C-\mcfabove{C}{\mcfatomno{4}}H([:-90]-(!\nobond{\hspace{-.45cm}5})CH_2-(!\nobond{\hspace{-.45cm}6})CH_3)-\mcfbelow{C}{\mcfatomno{3}}H([:90]-CH_3)-\mcfabove{C}{\mcfatomno{2}}H([:-90]-OH)-\mcfabove{C}{\mcfatomno{1}}H_3}
   }{3,4-dimetilexan-2-ol}
   \end{center}



   \chemfig{CH_3-CH([:-90]-CH_3)-CH_2-OH} \af
   \chemfig{CH_3-CH([:-90]-CH_3)-CH_2-CH([:-90]-OH)-CH_3}\af
   
   


#+end_export

#+latex: \end{myrule}

   


      
* Enol
** Enóis
     #+latex: \begin{mybox}{Enol}
  Substâncias  orgânicas  que  apresentam  hidroxila  ou oxidrila (-OH) ligada ao C com uma dupla ligação.


  #+begin_export latex
  \begin{center}
\chemfig{-@{OH1}C([:90]-)([:-90]-)=C([:90]-)([:-90]-)-O@{OH2}H}
\chemmove{
	\node[inner sep=2pt,fill=red,fill opacity=0.2,fit=(OH1) (OH2)]{};
    }
    \end{center}
#+end_export 

  #+latex: \end{mybox}
     #+begin_export latex
   \begin{myex}{Exemplo}
 \begin{center}  
 %  \chemname{
%   \chemfig{H_3{\color{red}C}-OH}}{{\color{red}Met}anol}\hspace{1cm}
   \chemname{
   \vspace{.3cm}
\chemfig{
           \mcfleft{\mcfatomno{4}}{C}H_3% 4
     -[:0]\mcfabove{C}{\mcfatomno{3}}H_2% 3
    -[:0]\mcfabove{C}{\mcfatomno{2}}H% 2
     =[:0]\mcfabove{C}{\mcfatomno{1}}H% 1
    -[:0]OH}% 
}
{But-1-en-1-ol}
\end{center}\
%
\end{myex}
#+end_export
   


* Fenol
**  Fenóis
#+latex: \begin{mybox}{Fenol}
  Substâncias  orgânicas  que  apresentam  hidroxila  ou oxidrila (-OH) ligada ao carbono do anel aromático.


  #+begin_export latex

\begin{tikzpicture}
\tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{*6(-=-=-(-OH)=-)}} \af
\tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{**6(-----(-OH)--)}} \af
\end{tikzpicture}

  #+end_export 
  #+latex: \end{mybox}

** Tipos de fénois
   #+begin_export latex
   \begin{myex}{Fénois}
   \centering
   \chemname{\chemfig{*6(-=(-OH)-=-=)}}{Hidroxi \\ Benzeno} \af 
   \chemname{\chemfig{**6(---(**6(------))---)}}{Naftaleno} \af 
   \chemname{\chemfig{**6(--(**6(-**6(------)-----))----)}}{Antraceno}
   \end{myex}
   #+end_export
   
** Nomenclatura dos Fénois

   - Na nomenclatura dos fénois a cadeia principal é o benzeno e a hidroxila torna-se radical chamado *hidróxi*.
   - O *hidróxi* é o radical principal para iniciar a contar a posição em caso de radicais presentes no anel benzênico.
   #+begin_export latex
\chemname{\chemfig{**6(----(-OH)--)}}{hidróxi benzeno} \af
\chemname{\chemfig{**6(---(-CH_3)-(-OH)--)}}{1-hidróxi-2-metil-benzeno} \af
\chemname{\chemfig{**6(--(-C_2H_5)--(-OH)--)}}{1-hidróxi-3-etil-benzeno} \af
\chemname{\chemfig{**6(---(-OH)-(-OH)--)}}{1,2-dihidroxi-benzeno} 
   #+end_export


* Aldeídos
** Aldeídos
   #+latex: \begin{mybox}{Aldeído}
   Os aldeídos apresentam o grupo carbonila na extremidade da cadeia.   


   #+begin_export latex
   \begin{center}
\begin{tikzpicture}
\tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{-[:30]-[:330]-[:30](-[:330,,,1]H)=[:90]O}} \hspace{.3 cm}
%\tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{**6(-----(-OH)--)}}
\end{tikzpicture}
\end{center}
   #+end_export
   #+latex: \end{mybox}   
   

** Nomenclatura dos Aldeídos


#+begin_export latex

\chemfig{H-[:150]\mcfatomno{1}(%
=[:90]O)-[:210]\mcfatomno{2}-[:150]\mcfatomno{3}}


#+end_export
   
* Cetonas

** Cetonas

#+latex: \begin{mybox}{Cetonas}
As cetonas apresentam o grupo carbonila,sendo este carbono secundário.
#+begin_export latex
   \begin{center}
   \begin{tikzpicture}
   \tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{C-C([:90]=O)-C}} \hspace{.3 cm}
   \end{tikzpicture}
   \end{center}
   #+end_export
#+latex: \end{mybox}
   

* Ácido Carboxílicos
** Ácidos Carboxílicos
    #+latex: \begin{mybox}{Ácidos Carboxílicos}
   Os ácidos carboxílicos são compostos caracterizados pela
   presença do grupo *carboxila*, formado pela união dos grupos carbonila e hidroxila.


   #+begin_export latex
   \begin{center}
   \begin{tikzpicture}
   \tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{-C([:30]=O)([:330]-OH)}} \hspace{.3 cm}
   \end{tikzpicture}
   \end{center}
   #+end_export
   #+latex: \end{mybox}   


* Ésteres
    #+latex: \begin{mybox}{Ésteres}
    Os ésteres orgânicos são caracterizados pelo grupo funcional:
   #+begin_export latex
   \begin{center}
   \begin{tikzpicture}
   \tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{R-C([:90]=O)-O-R'}} \hspace{.3 cm}
   \end{tikzpicture}
   \end{center}
   #+end_export
   Simplificadamente podemos considerar queos ésteres
   se originam a partir da substituição do hidrogênio do grupo OH de um
   ácido carboxílico por um radical orgânico (R).
   #+latex: \end{mybox}

   
* Éteres

** Éteres

    #+latex: \begin{mybox}{Éteres}
Os éteres apresentam um átomo de oxigênio(O) ligado a dois radicais orgânicos.
Seu grupo funcional é representado por:

#+begin_export latex
   \begin{center}
   \begin{tikzpicture}
   \tcbox[enhanced,sharp corners,colback=red!10,colframe=red]{\chemfig{R-O-R'}} \hspace{.3 cm}
   \end{tikzpicture}
   \end{center}
   #+end_export

   #+latex: \end{mybox}





* Anidridos

** Anidridos
