#+TITLE: 

* Soluções

** Soluções

- Solução: :: é uma mistura homogênea de soluto e solvente
- Solvente: :: Componente cujo estado físico é preservado.
- Soluto: :: Dissolvido no solvente

   *Observação:* /Se todos os componentes estiverem no mesmo estado físico, o solvente é aquele presente em maior quantidade./

** Solubilidade /versus/ Temperatura
 :PROPERTIES:
   :BEAMER_envargs: [t]
   :END:

*** A block                                                             :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.4
    :END:
    
#+begin_export latex
\begin{figure}
\centering 
\begin{tikzpicture}[scale=0.5, transform shape]]
	\begin{axis}[
       ylabel=Solubilidade g/g \ch{H2O},
		xlabel=Temperatura / \si{\celsius},
		title=Curva de Solubilidade, 
		legend style={draw=none},
		legend pos=north west]
		%% KNO3
	\addplot[color=red,mark=*] coordinates {
		(0,13.25)
		(20,31.66)
		(40,63.9)
		(60,109.9)
		(80,169)
		(100,245.2)
	};
	%%% KI
	\addplot[color=blue,mark=*] coordinates {
		(0,127.8)
		(20,144.51)
		(40,161)
		(60,176.2)
		(80,191.5)
		(100,208)
	};
	%% KClO4
	\addplot[color=black,mark=*] coordinates {
		(0,0.76)
		(20,1.73)
		(40,3.63)
		(60,7.18)
		(80,13.38)
		(100,22.2)
	};
	%% NaCl
	%35.6	35.8	36.42	37.05	38.05	39.2
	\addplot[color=green,mark=*] coordinates {
		(0,35.6)
		(20,35.8)
		(40,36.42)
		(60,37.05)
		(80,38.05)
		(100,39.2)
	};
	\legend{\ch{KNO3}, KI, \ch{KC$\ell$O4}, \ch{NaC$\ell$}}
	\end{axis}
\end{tikzpicture}
\caption{Curvas de Solubilidade}
\end{figure}
#+end_export

*** A screenshot                                            :BMCOL:B_example:
    :PROPERTIES:
    :BEAMER_col: 0.6
    :END:
- A solubilidade de uma substância é a quantidade máxima de uma substância que pode ser dissolvida em uma quantidade fixa de solvente a uma determinada temperatura.
- A solubilidade de uma substância geralmente aumenta com a temperatura.
- As moléculas da substância têm mais energia cinética a temperaturas mais altas, o que torna mais provável que elas colidam com as moléculas do solvente e se dissolvam.


* Densidade
 
** Densidade


- Densidade das soluções é uma propriedade física dessas misturas homogêneas, ou seja, pode ser obtida por meio da determinação laboratorial de algumas variáveis, a exemplo da temperatura, peso, volume.

  #+begin_export latex
  \begin{tcolorbox}[ams align*]
  \mathcal{d}=\frac{m}{v}
  \end{tcolorbox}
  #+end_export

  - A densidade pode ser expressa em \unit{\gram\per\litre}, \unit{\gram\per\ml}, \unit{\gram\per\cubic\centi\metre} , entre outras unidades.

 - A densidade é uma propriedade específica da matéria, podendo ser utilizada para identificar substâncias, determinar propriedades da matéria e controlar a qualidade.

** Exemplo

#+begin_question
Uma quantidade igual a 40,0 g de \ch{KNO3} foi dissolvida em 190 \unit{\gram\per\cubic\centi\metre} de água, resultando em 200 \unit{\gram\per\cubic\centi\metre} de solução. Calcule a densidade em \unit{\gram\per\litre} dessa solução. Considere: $\mathcal{d}_{\text{água}}$ = 1 \unit{\gram\per\ml}.
#+end_question 



** 

#+ATTR_LATEX: :options [print=true]
 #+begin_answer
- 1: :: Calcular massa do solvente.
 #+begin_export latex
\begin{align*}
\mathcal{d}=\frac{m_1}{v} \Rightarrow 1 = \frac{m_1}{190} \Rightarrow m_1= 190\ \unit{g} 
\end{align*}
 #+end_export

- 2: :: Transformação da unidade do volume de cm^3 para L. 1 cm^3 = 1 mL. 200 mL = 0,2 L
- 3: :: Cálculo da densidade da solução.
 #+begin_export latex
\begin{align*}
\mathcal{d} = \frac{m_1 + m_2}{V} \Rightarrow \mathcal{d} = \frac{40 + 190}{0,2}\\
\mathcal{d} = 1150 ~\unit{\gram\per\litre}
\end{align*}
 #+end_export
       
 #+end_answer
